default: &default
  timeout: 5000
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: "auto@123"
  database: stubs
  host: aadhi-mysql

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
